export const ADD_NODE = 'ADD_NODE'
export const REMOVE_NODE = 'REMOVE_NODE'
export const CHANGE_NODE_POSITION = 'CHANGE_NODE_POSITION'
export const CHANGE_ACTIVE_NODE = 'CHANGE_ACTIVE_NODE'
export const CLEAR_ALL_NODES = 'CLEAR_ALL_NODES'
export const SET_NODES = 'SET_NODES'

export const ADD_LINK = 'ADD_LINK'
export const REMOVE_LINK = 'REMOVE_LINK'

export const UPDATE_CALC_TABLE = 'UPDATE_CALC_TABLE'

export const NODE_SELECTOR_ON = 'NODE_SELECTOR_ON'
export const NODE_SELECTOR_OFF = 'NODE_SELECTOR_OFF'

export const SET_ACTIVE_NODE = 'SET_ACTIVE_NODE'
export const ACTIVE_NODE_OPTIONS_ON = 'ACTIVE_NODE_OPTIONS_ON'
export const ACTIVE_NODE_OPTIONS_OFF = 'ACTIVE_NODE_OPTIONS_OFF'

export const UPDATE_DBTABLES_META = 'UPDATE_DBTABLES_META'

export const UPDATE_RESULTS = 'UPDATE_RESULTS'



// Group selection
export const SET_MULTISELECT_ON = 'SET_MULTISELECT_ON'
export const SET_MULTISELECT_OFF = 'SET_MULTISELECT_OFF'
export const MULTISELECT_START_XY = 'MULTISELECT_START_XY'
export const MULTISELECT_END_XY = 'MULTISELECT_END_XY'
// multiselect_move
